name: Check Python

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11-dev"]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python-poetry-env
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Run flake8"
        run: |
          poetry run pre-commit run --all-files flake8
      - name: "Run mypy"
        run: |
          poetry run pre-commit run --all-files mypy
      - name: Test with pytest
        run: |
          poetry run pytest tests/
